# Generated by Django 6.0.4 on 2026-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
